FROM python:3.10-slim

WORKDIR /triton

RUN pip install --no-cache-dir \
    "tritonclient[http]" \
    fastapi \
    uvicorn \
    numpy \
    pandas \
    python-multipart

COPY . .

EXPOSE 8080

CMD ["uvicorn", "web_app:app", "--host", "0.0.0.0", "--port", "8080"]
