_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": DeviceStatsMonitor.on_validation_batch_start/cpu_vm_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_train_batch_end/cpu_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_train_batch_end/cpu_swap_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_validation_batch_end/cpu_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": lr-Adam
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_train_batch_start/cpu_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_train_batch_end/cpu_vm_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_validation_batch_start/cpu_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_validation_batch_end/cpu_swap_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_train_batch_start/cpu_vm_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_train_batch_start/cpu_swap_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_validation_batch_start/cpu_swap_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": DeviceStatsMonitor.on_validation_batch_end/cpu_vm_percent
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 9
                - 40
                - 50
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 40
                - 50
                - 53
                - 55
                - 103
                - 105
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.9
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
lr:
    value: 0.001
model:
    value: null
